### ISSUE TITLE
label: Question Will this work on ethernet router

### ISSUE THREAD

**Issue by latapata** [JelmerT/thingsquare-mist#1]
Hello

I am trying to run this file and I seem soubtful about htis program connecting to internet with the enc28j60. Because no where in the contiki main code the SPI communication has been initialised. Also If I have to directly connect the cc2538dk to the internet via slip then there is no possibility to do that i suppose. 

if anybody has faced the same problem please discuss it here

**Comment by JelmerT** [comment]
This is very old, non-working, code. It's not up-to-date with the main-line contiki branch.
If you are interested in the Thingsquare mist protocol, you're beter of contacting them directly. If you want to get the enc28j60 working, have a look in the main contiki repo.
