### ISSUE TITLE
compilation terminated

### ISSUE THREAD

**Issue by latapata** [JelmerT/thingsquare-mist#2]
user@instant-contiki:~/thingsquare-mist-master/examples/tcp-socket$ make
TARGET not defined, using target 'native'
fatal: Not a git repository: '../../contiki/.git'
mkdir obj_native
  CC        ../../apps/aes/aes.c
  CC        ../../apps/aes/aes-ccm.c
../../apps/aes/aes-ccm.c:35:21: fatal error: net/uip.h: No such file or directory
compilation terminated.
make: *** [obj_native/aes-ccm.o] Error 1

**Comment by JelmerT** [comment]
see #1
