### ISSUE TITLE
No Pin or Name Display but only 'Connected' Displayed on LCD Screen of connected Thingsquare nodes - Indrajit

### ISSUE THREAD

**Issue by IndrajitAC** [JelmerT/thingsquare-mist#3]
Hi,

We are working on the Thingsquare IoT cloud system based on CC2538 EM on the SmartRF06 EB and are highly impressed with it. Until December, the setup was working perfectly fine with each CC2538 chip displaying its pin (or its name given by us for the already registered CC2538 devices) to connect to the Thingsquare Webpage https://demo.thsq.io/

However, now we are facing the following issue: We are unable to see (& hence select and delete) connected Thingsquare nodes on the Thingsquare Webpage

Each CC2538 chip is simply displaying ‘Connected’ (as shown in the attached picture) and not displaying either its pin or its customized name (if already registered earlier) when connected to Thingsquare via the Ethernet router. Owing to this, we cannot see the connected CC2538 device on the Thingsquare Webpage or control the device via it. Another thing we noticed is that even the RUN, PAUSE, REBOOT and BLINK click buttons within the develop tab are inactive.

How can I restore the normal functioning of the CC2538 nodes in conjunction with the Thingsquare webpage?
![img_2757](https://cloud.githubusercontent.com/assets/11133029/6316433/0add0cf8-ba8b-11e4-8c12-5ce07eb06112.JPG)
![capture 1](https://cloud.githubusercontent.com/assets/11133029/6316434/14334916-ba8b-11e4-9497-ac4379fe51ea.JPG)

I earnestly request your kind selves to help me in this regard.

Thanking you,
Indrajit

**Comment by JelmerT** [comment]
Hi @IndrajitAC, this repo is a very old fork of the thingsquare code, I'm not affiliated with @thingsquare in any way. 

If you need support from them, I advice you to contact them directly here https://github.com/thingsquare or at www.thingsquare.com
